-- Create the user 
create user LUNENDER
  default tablespace USERS
  temporary tablespace TEMP
  profile DEFAULT
  password expire;
-- Grant/Revoke role privileges 
grant dba to LUNENDER with admin option;
-- Grant/Revoke system privileges 
grant administer any sql tuning set to LUNENDER;
grant administer database trigger to LUNENDER;
grant administer sql management object to LUNENDER;
grant administer sql tuning set to LUNENDER;
grant advisor to LUNENDER;
grant alter any assembly to LUNENDER;
grant alter any cluster to LUNENDER;
grant alter any cube to LUNENDER;
grant alter any cube dimension to LUNENDER;
grant alter any dimension to LUNENDER;
grant alter any edition to LUNENDER;
grant alter any evaluation context to LUNENDER;
grant alter any index to LUNENDER;
grant alter any indextype to LUNENDER;
grant alter any library to LUNENDER;
grant alter any materialized view to LUNENDER;
grant alter any mining model to LUNENDER;
grant alter any operator to LUNENDER;
grant alter any outline to LUNENDER;
grant alter any procedure to LUNENDER;
grant alter any role to LUNENDER;
grant alter any rule to LUNENDER;
grant alter any rule set to LUNENDER;
grant alter any sequence to LUNENDER;
grant alter any sql profile to LUNENDER;
grant alter any table to LUNENDER;
grant alter any trigger to LUNENDER;
grant alter any type to LUNENDER;
grant alter database to LUNENDER;
grant alter profile to LUNENDER;
grant alter resource cost to LUNENDER;
grant alter rollback segment to LUNENDER;
grant alter session to LUNENDER;
grant alter system to LUNENDER;
grant alter tablespace to LUNENDER;
grant alter user to LUNENDER;
grant analyze any to LUNENDER;
grant audit any to LUNENDER;
grant audit system to LUNENDER;
grant backup any table to LUNENDER;
grant become user to LUNENDER;
grant change notification to LUNENDER;
grant comment any mining model to LUNENDER;
grant comment any table to LUNENDER;
grant create any assembly to LUNENDER;
grant create any cluster to LUNENDER;
grant create any context to LUNENDER;
grant create any cube to LUNENDER;
grant create any cube build process to LUNENDER;
grant create any cube dimension to LUNENDER;
grant create any dimension to LUNENDER;
grant create any directory to LUNENDER;
grant create any edition to LUNENDER;
grant create any evaluation context to LUNENDER;
grant create any index to LUNENDER;
grant create any indextype to LUNENDER;
grant create any job to LUNENDER;
grant create any library to LUNENDER;
grant create any materialized view to LUNENDER;
grant create any measure folder to LUNENDER;
grant create any mining model to LUNENDER;
grant create any operator to LUNENDER;
grant create any outline to LUNENDER;
grant create any procedure to LUNENDER;
grant create any rule to LUNENDER;
grant create any rule set to LUNENDER;
grant create any sequence to LUNENDER;
grant create any sql profile to LUNENDER;
grant create any synonym to LUNENDER;
grant create any table to LUNENDER;
grant create any trigger to LUNENDER;
grant create any type to LUNENDER;
grant create any view to LUNENDER;
grant create assembly to LUNENDER;
grant create cluster to LUNENDER;
grant create cube to LUNENDER;
grant create cube build process to LUNENDER;
grant create cube dimension to LUNENDER;
grant create database link to LUNENDER;
grant create dimension to LUNENDER;
grant create evaluation context to LUNENDER;
grant create external job to LUNENDER;
grant create indextype to LUNENDER;
grant create job to LUNENDER;
grant create library to LUNENDER;
grant create materialized view to LUNENDER;
grant create measure folder to LUNENDER;
grant create mining model to LUNENDER;
grant create operator to LUNENDER;
grant create procedure to LUNENDER;
grant create profile to LUNENDER;
grant create public database link to LUNENDER;
grant create public synonym to LUNENDER;
grant create role to LUNENDER;
grant create rollback segment to LUNENDER;
grant create rule to LUNENDER;
grant create rule set to LUNENDER;
grant create sequence to LUNENDER;
grant create session to LUNENDER;
grant create synonym to LUNENDER;
grant create table to LUNENDER;
grant create tablespace to LUNENDER;
grant create trigger to LUNENDER;
grant create type to LUNENDER;
grant create user to LUNENDER;
grant create view to LUNENDER;
grant debug any procedure to LUNENDER;
grant debug connect session to LUNENDER;
grant delete any cube dimension to LUNENDER;
grant delete any measure folder to LUNENDER;
grant delete any table to LUNENDER;
grant dequeue any queue to LUNENDER;
grant drop any assembly to LUNENDER;
grant drop any cluster to LUNENDER;
grant drop any context to LUNENDER;
grant drop any cube to LUNENDER;
grant drop any cube build process to LUNENDER;
grant drop any cube dimension to LUNENDER;
grant drop any dimension to LUNENDER;
grant drop any directory to LUNENDER;
grant drop any edition to LUNENDER;
grant drop any evaluation context to LUNENDER;
grant drop any index to LUNENDER;
grant drop any indextype to LUNENDER;
grant drop any library to LUNENDER;
grant drop any materialized view to LUNENDER;
grant drop any measure folder to LUNENDER;
grant drop any mining model to LUNENDER;
grant drop any operator to LUNENDER;
grant drop any outline to LUNENDER;
grant drop any procedure to LUNENDER;
grant drop any role to LUNENDER;
grant drop any rule to LUNENDER;
grant drop any rule set to LUNENDER;
grant drop any sequence to LUNENDER;
grant drop any sql profile to LUNENDER;
grant drop any synonym to LUNENDER;
grant drop any table to LUNENDER;
grant drop any trigger to LUNENDER;
grant drop any type to LUNENDER;
grant drop any view to LUNENDER;
grant drop profile to LUNENDER;
grant drop public database link to LUNENDER;
grant drop public synonym to LUNENDER;
grant drop rollback segment to LUNENDER;
grant drop tablespace to LUNENDER;
grant drop user to LUNENDER;
grant enqueue any queue to LUNENDER;
grant execute any assembly to LUNENDER;
grant execute any class to LUNENDER;
grant execute any evaluation context to LUNENDER;
grant execute any indextype to LUNENDER;
grant execute any library to LUNENDER;
grant execute any operator to LUNENDER;
grant execute any procedure to LUNENDER;
grant execute any program to LUNENDER;
grant execute any rule to LUNENDER;
grant execute any rule set to LUNENDER;
grant execute any type to LUNENDER;
grant execute assembly to LUNENDER;
grant export full database to LUNENDER;
grant flashback any table to LUNENDER;
grant flashback archive administer to LUNENDER;
grant force any transaction to LUNENDER;
grant force transaction to LUNENDER;
grant global query rewrite to LUNENDER;
grant grant any object privilege to LUNENDER;
grant grant any privilege to LUNENDER;
grant grant any role to LUNENDER;
grant import full database to LUNENDER;
grant insert any cube dimension to LUNENDER;
grant insert any measure folder to LUNENDER;
grant insert any table to LUNENDER;
grant lock any table to LUNENDER;
grant manage any file group to LUNENDER;
grant manage any queue to LUNENDER;
grant manage file group to LUNENDER;
grant manage scheduler to LUNENDER;
grant manage tablespace to LUNENDER;
grant merge any view to LUNENDER;
grant on commit refresh to LUNENDER;
grant query rewrite to LUNENDER;
grant read any file group to LUNENDER;
grant restricted session to LUNENDER;
grant resumable to LUNENDER;
grant select any cube to LUNENDER;
grant select any cube dimension to LUNENDER;
grant select any mining model to LUNENDER;
grant select any sequence to LUNENDER;
grant select any table to LUNENDER;
grant select any transaction to LUNENDER;
grant under any table to LUNENDER;
grant under any type to LUNENDER;
grant under any view to LUNENDER;
grant unlimited tablespace to LUNENDER;
grant update any cube to LUNENDER;
grant update any cube build process to LUNENDER;
grant update any cube dimension to LUNENDER;
grant update any table to LUNENDER;
