drop user wms cascade;
-- Create the user 
create user wms
  default tablespace USERS
  temporary tablespace TEMP
  profile DEFAULT
  identified by wwmmss2013;
-- Grant/Revoke role privileges 
grant dba to wms with admin option;
-- Grant/Revoke system privileges 
grant administer any sql tuning set to wms;
grant administer database trigger to wms;
grant administer sql management object to wms;
grant administer sql tuning set to wms;
grant advisor to wms;
grant alter any assembly to wms;
grant alter any cluster to wms;
grant alter any cube to wms;
grant alter any cube dimension to wms;
grant alter any dimension to wms;
grant alter any edition to wms;
grant alter any evaluation context to wms;
grant alter any index to wms;
grant alter any indextype to wms;
grant alter any library to wms;
grant alter any materialized view to wms;
grant alter any mining model to wms;
grant alter any operator to wms;
grant alter any outline to wms;
grant alter any procedure to wms;
grant alter any role to wms;
grant alter any rule to wms;
grant alter any rule set to wms;
grant alter any sequence to wms;
grant alter any sql profile to wms;
grant alter any table to wms;
grant alter any trigger to wms;
grant alter any type to wms;
grant alter database to wms;
grant alter profile to wms;
grant alter resource cost to wms;
grant alter rollback segment to wms;
grant alter session to wms;
grant alter system to wms;
grant alter tablespace to wms;
grant alter user to wms;
grant analyze any to wms;
grant audit any to wms;
grant audit system to wms;
grant backup any table to wms;
grant become user to wms;
grant change notification to wms;
grant comment any mining model to wms;
grant comment any table to wms;
grant create any assembly to wms;
grant create any cluster to wms;
grant create any context to wms;
grant create any cube to wms;
grant create any cube build process to wms;
grant create any cube dimension to wms;
grant create any dimension to wms;
grant create any directory to wms;
grant create any edition to wms;
grant create any evaluation context to wms;
grant create any index to wms;
grant create any indextype to wms;
grant create any job to wms;
grant create any library to wms;
grant create any materialized view to wms;
grant create any measure folder to wms;
grant create any mining model to wms;
grant create any operator to wms;
grant create any outline to wms;
grant create any procedure to wms;
grant create any rule to wms;
grant create any rule set to wms;
grant create any sequence to wms;
grant create any sql profile to wms;
grant create any synonym to wms;
grant create any table to wms;
grant create any trigger to wms;
grant create any type to wms;
grant create any view to wms;
grant create assembly to wms;
grant create cluster to wms;
grant create cube to wms;
grant create cube build process to wms;
grant create cube dimension to wms;
grant create database link to wms;
grant create dimension to wms;
grant create evaluation context to wms;
grant create external job to wms;
grant create indextype to wms;
grant create job to wms;
grant create library to wms;
grant create materialized view to wms;
grant create measure folder to wms;
grant create mining model to wms;
grant create operator to wms;
grant create procedure to wms;
grant create profile to wms;
grant create public database link to wms;
grant create public synonym to wms;
grant create role to wms;
grant create rollback segment to wms;
grant create rule to wms;
grant create rule set to wms;
grant create sequence to wms;
grant create session to wms;
grant create synonym to wms;
grant create table to wms;
grant create tablespace to wms;
grant create trigger to wms;
grant create type to wms;
grant create user to wms;
grant create view to wms;
grant debug any procedure to wms;
grant debug connect session to wms;
grant delete any cube dimension to wms;
grant delete any measure folder to wms;
grant delete any table to wms;
grant dequeue any queue to wms;
grant drop any assembly to wms;
grant drop any cluster to wms;
grant drop any context to wms;
grant drop any cube to wms;
grant drop any cube build process to wms;
grant drop any cube dimension to wms;
grant drop any dimension to wms;
grant drop any directory to wms;
grant drop any edition to wms;
grant drop any evaluation context to wms;
grant drop any index to wms;
grant drop any indextype to wms;
grant drop any library to wms;
grant drop any materialized view to wms;
grant drop any measure folder to wms;
grant drop any mining model to wms;
grant drop any operator to wms;
grant drop any outline to wms;
grant drop any procedure to wms;
grant drop any role to wms;
grant drop any rule to wms;
grant drop any rule set to wms;
grant drop any sequence to wms;
grant drop any sql profile to wms;
grant drop any synonym to wms;
grant drop any table to wms;
grant drop any trigger to wms;
grant drop any type to wms;
grant drop any view to wms;
grant drop profile to wms;
grant drop public database link to wms;
grant drop public synonym to wms;
grant drop rollback segment to wms;
grant drop tablespace to wms;
grant drop user to wms;
grant enqueue any queue to wms;
grant execute any assembly to wms;
grant execute any class to wms;
grant execute any evaluation context to wms;
grant execute any indextype to wms;
grant execute any library to wms;
grant execute any operator to wms;
grant execute any procedure to wms;
grant execute any program to wms;
grant execute any rule to wms;
grant execute any rule set to wms;
grant execute any type to wms;
grant execute assembly to wms;
grant export full database to wms;
grant flashback any table to wms;
grant flashback archive administer to wms;
grant force any transaction to wms;
grant force transaction to wms;
grant global query rewrite to wms;
grant grant any object privilege to wms;
grant grant any privilege to wms;
grant grant any role to wms;
grant import full database to wms;
grant insert any cube dimension to wms;
grant insert any measure folder to wms;
grant insert any table to wms;
grant lock any table to wms;
grant manage any file group to wms;
grant manage any queue to wms;
grant manage file group to wms;
grant manage scheduler to wms;
grant manage tablespace to wms;
grant merge any view to wms;
grant on commit refresh to wms;
grant query rewrite to wms;
grant read any file group to wms;
grant restricted session to wms;
grant resumable to wms;
grant select any cube to wms;
grant select any cube dimension to wms;
grant select any mining model to wms;
grant select any sequence to wms;
grant select any table to wms;
grant select any transaction to wms;
grant under any table to wms;
grant under any type to wms;
grant under any view to wms;
grant unlimited tablespace to wms;
grant update any cube to wms;
grant update any cube build process to wms;
grant update any cube dimension to wms;
grant update any table to wms;
