drop user aflex cascade;
-- Create the user 
create user aflex
  default tablespace USERS
  temporary tablespace TEMP
  profile DEFAULT
  identified by aflex;
-- Grant/Revoke role privileges 
grant dba to aflex with admin option;
-- Grant/Revoke system privileges 
grant administer any sql tuning set to aflex;
grant administer database trigger to aflex;
grant administer sql management object to aflex;
grant administer sql tuning set to aflex;
grant advisor to aflex;
grant alter any assembly to aflex;
grant alter any cluster to aflex;
grant alter any cube to aflex;
grant alter any cube dimension to aflex;
grant alter any dimension to aflex;
grant alter any edition to aflex;
grant alter any evaluation context to aflex;
grant alter any index to aflex;
grant alter any indextype to aflex;
grant alter any library to aflex;
grant alter any materialized view to aflex;
grant alter any mining model to aflex;
grant alter any operator to aflex;
grant alter any outline to aflex;
grant alter any procedure to aflex;
grant alter any role to aflex;
grant alter any rule to aflex;
grant alter any rule set to aflex;
grant alter any sequence to aflex;
grant alter any sql profile to aflex;
grant alter any table to aflex;
grant alter any trigger to aflex;
grant alter any type to aflex;
grant alter database to aflex;
grant alter profile to aflex;
grant alter resource cost to aflex;
grant alter rollback segment to aflex;
grant alter session to aflex;
grant alter system to aflex;
grant alter tablespace to aflex;
grant alter user to aflex;
grant analyze any to aflex;
grant audit any to aflex;
grant audit system to aflex;
grant backup any table to aflex;
grant become user to aflex;
grant change notification to aflex;
grant comment any mining model to aflex;
grant comment any table to aflex;
grant create any assembly to aflex;
grant create any cluster to aflex;
grant create any context to aflex;
grant create any cube to aflex;
grant create any cube build process to aflex;
grant create any cube dimension to aflex;
grant create any dimension to aflex;
grant create any directory to aflex;
grant create any edition to aflex;
grant create any evaluation context to aflex;
grant create any index to aflex;
grant create any indextype to aflex;
grant create any job to aflex;
grant create any library to aflex;
grant create any materialized view to aflex;
grant create any measure folder to aflex;
grant create any mining model to aflex;
grant create any operator to aflex;
grant create any outline to aflex;
grant create any procedure to aflex;
grant create any rule to aflex;
grant create any rule set to aflex;
grant create any sequence to aflex;
grant create any sql profile to aflex;
grant create any synonym to aflex;
grant create any table to aflex;
grant create any trigger to aflex;
grant create any type to aflex;
grant create any view to aflex;
grant create assembly to aflex;
grant create cluster to aflex;
grant create cube to aflex;
grant create cube build process to aflex;
grant create cube dimension to aflex;
grant create database link to aflex;
grant create dimension to aflex;
grant create evaluation context to aflex;
grant create external job to aflex;
grant create indextype to aflex;
grant create job to aflex;
grant create library to aflex;
grant create materialized view to aflex;
grant create measure folder to aflex;
grant create mining model to aflex;
grant create operator to aflex;
grant create procedure to aflex;
grant create profile to aflex;
grant create public database link to aflex;
grant create public synonym to aflex;
grant create role to aflex;
grant create rollback segment to aflex;
grant create rule to aflex;
grant create rule set to aflex;
grant create sequence to aflex;
grant create session to aflex;
grant create synonym to aflex;
grant create table to aflex;
grant create tablespace to aflex;
grant create trigger to aflex;
grant create type to aflex;
grant create user to aflex;
grant create view to aflex;
grant debug any procedure to aflex;
grant debug connect session to aflex;
grant delete any cube dimension to aflex;
grant delete any measure folder to aflex;
grant delete any table to aflex;
grant dequeue any queue to aflex;
grant drop any assembly to aflex;
grant drop any cluster to aflex;
grant drop any context to aflex;
grant drop any cube to aflex;
grant drop any cube build process to aflex;
grant drop any cube dimension to aflex;
grant drop any dimension to aflex;
grant drop any directory to aflex;
grant drop any edition to aflex;
grant drop any evaluation context to aflex;
grant drop any index to aflex;
grant drop any indextype to aflex;
grant drop any library to aflex;
grant drop any materialized view to aflex;
grant drop any measure folder to aflex;
grant drop any mining model to aflex;
grant drop any operator to aflex;
grant drop any outline to aflex;
grant drop any procedure to aflex;
grant drop any role to aflex;
grant drop any rule to aflex;
grant drop any rule set to aflex;
grant drop any sequence to aflex;
grant drop any sql profile to aflex;
grant drop any synonym to aflex;
grant drop any table to aflex;
grant drop any trigger to aflex;
grant drop any type to aflex;
grant drop any view to aflex;
grant drop profile to aflex;
grant drop public database link to aflex;
grant drop public synonym to aflex;
grant drop rollback segment to aflex;
grant drop tablespace to aflex;
grant drop user to aflex;
grant enqueue any queue to aflex;
grant execute any assembly to aflex;
grant execute any class to aflex;
grant execute any evaluation context to aflex;
grant execute any indextype to aflex;
grant execute any library to aflex;
grant execute any operator to aflex;
grant execute any procedure to aflex;
grant execute any program to aflex;
grant execute any rule to aflex;
grant execute any rule set to aflex;
grant execute any type to aflex;
grant execute assembly to aflex;
grant export full database to aflex;
grant flashback any table to aflex;
grant flashback archive administer to aflex;
grant force any transaction to aflex;
grant force transaction to aflex;
grant global query rewrite to aflex;
grant grant any object privilege to aflex;
grant grant any privilege to aflex;
grant grant any role to aflex;
grant import full database to aflex;
grant insert any cube dimension to aflex;
grant insert any measure folder to aflex;
grant insert any table to aflex;
grant lock any table to aflex;
grant manage any file group to aflex;
grant manage any queue to aflex;
grant manage file group to aflex;
grant manage scheduler to aflex;
grant manage tablespace to aflex;
grant merge any view to aflex;
grant on commit refresh to aflex;
grant query rewrite to aflex;
grant read any file group to aflex;
grant restricted session to aflex;
grant resumable to aflex;
grant select any cube to aflex;
grant select any cube dimension to aflex;
grant select any mining model to aflex;
grant select any sequence to aflex;
grant select any table to aflex;
grant select any transaction to aflex;
grant under any table to aflex;
grant under any type to aflex;
grant under any view to aflex;
grant unlimited tablespace to aflex;
grant update any cube to aflex;
grant update any cube build process to aflex;
grant update any cube dimension to aflex;
grant update any table to aflex;
